vpc-name      = "github-vpc"
igw-name      = "github-igw"
subnet-name   = "github-subnet"
rt-name       = "github-route-table"
sg-name       = "github-sg"
instance-name = "github-server"
key-name      = "poc-key-pair"
iam-role      = "github-iam-role"
