name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-east-1"
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ECR_REPO_NAME: ${{ secrets.AWS_ECR_REPO_NAME }}
  REPOSITORY_URI: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPO_NAME }}"
  GIT_USER_NAME: "patilkaran1997"
  GIT_REPO_NAME: "-End-to-End-Kubernetes-Three-Tier-DevSecOps-Project"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@v1.3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Analysis
        run: |
          cd Application-Code/frontend
          sonar-scanner -Dsonar.projectName=three-tier-frontend -Dsonar.projectKey=three-tier-frontend

      - name: Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: OWASP Dependency-Check
        run: |
          cd Application-Code/frontend
          dependency-check.sh --scan ./ --disableYarnAudit --disableNodeAudit

      - name: Trivy File Scan
        run: |
          cd Application-Code/frontend
          trivy fs . > trivyfs.txt

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ env.REPOSITORY_URI }}
      
      - name: Docker Build and Push
        run: |
          cd Application-Code/frontend
          docker build -t ${{ env.AWS_ECR_REPO_NAME }} .
          docker tag ${{ env.AWS_ECR_REPO_NAME }} ${{ env.REPOSITORY_URI }}:${{ github.run_number }}
          docker push ${{ env.REPOSITORY_URI }}:${{ github.run_number }}

      - name: Trivy Image Scan
        run: |
          trivy image ${{ env.REPOSITORY_URI }}:${{ github.run_number }} > trivyimage.txt

      - name: Update Deployment File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "patilkaran1997@gmail.com"
          git config user.name "${{ env.GIT_USER_NAME }}"
          cd Kubernetes-Manifests-file/Frontend
          imageTag=$(grep -oP '(?<=frontend:)[^ ]+' deployment.yaml)
          sed -i "s/${{ env.AWS_ECR_REPO_NAME }}:${imageTag}/${{ env.AWS_ECR_REPO_NAME }}:${{ github.run_number }}/" deployment.yaml
          git add deployment.yaml
          git commit -m "Update deployment Image to version ${{ github.run_number }}"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.GIT_USER_NAME }}/${{ env.GIT_REPO_NAME }} HEAD:main

